### ISSUE TITLE
Using 'console.debug'

### ISSUE THREAD

**Issue by parithon** [clarkio/vscode-twitch-highlighter#33]
Not entirely sure what the issue is with my IDE but it appears to be missing the `console.debug` function. See the supporting attachments. I propose, unless somebody has a solution for me, to use `console.log` instead of `console.debug`.

![image](https://user-images.githubusercontent.com/8602418/51797232-8161a200-21b4-11e9-909c-de6a67eb28f2.png)
![image](https://user-images.githubusercontent.com/8602418/51797234-83c3fc00-21b4-11e9-9576-860242ab0644.png)

**Comment by clarkio** [comment]
Thanks for digging into `console.debug` more and sharing this information. Looks like all the `console.debug` instances have been removed so closing this issue. I briefly checked closed PR's and didn't see which one included the changes that addressed this issue. If you know offhand please tag it otherwise no big deal.

**Comment by parithon** [comment]
> I briefly checked closed PR's and didn't see which one included the changes that addressed this issue. If you know offhand please tag it otherwise no big deal.

I believe it was #36 which now includes this issue for historical record.
