### ISSUE TITLE
Determine Usage of Twitch Logo

### ISSUE THREAD

**Issue by clarkio** [clarkio/vscode-twitch-highlighter#56]
After reading through the [Twitch Trademark Guide](https://www.twitch.tv/p/legal/trademark) and the details in their [Brand documentation](https://www.twitch.tv/p/brand) it seems like it's ok to use the Glitch logo so long as it has no alterations or color changes.

In our use of the Glitch logo, we are not making any alterations or color changes however the theming with VS Code will override the logo colors. This is something we need to determine is in alignment with the proper usage of the logo or not.

**Comment by parithon** [comment]
I received the following reply from Twitch about their Glitch Icon: 

> Hello Parithon,
> 
> Thank you for reaching out to us. We are happy to hear your interest in building an extension! Unfortunately, our policies do not allow the usage of the Twitch Glitch, or Twitch logo in any capacity, according to policy 4.3
> 
> For a full list of policies, please take a look here: https://dev.twitch.tv/docs/extensions/guidelines-and-policies/

With this in mind, and because we plan on expanding the extension to support other chat services (such as Mixer) we should drop all third-party branding from our icon.

![highlightericon](https://github.com/clarkio/vscode-twitch-highlighter/blob/master/resources/highlighterIcon.png?raw=true)

**Comment by parithon** [comment]
Closing since the issue was resolved.
