### ISSUE TITLE
Start/Stop Chat button position

### ISSUE THREAD

**Issue by parithon** [clarkio/vscode-twitch-highlighter#78]
I've noticed that other extensions use the left side of the status bar to present their buttons to connect to services (e.g. live share). Should we keep the position of the start/stop button on the right, or move it to the left?

**Comment by clarkio** [comment]
I think move it to the left to follow that convention. Also I've heard it tends to be frowned upon for extensions to add icons to the Activity Bar. We should consider adding the tree view as a collapsible region in the file explorer and debug views instead. No an urgent issue but something to consider along the same lines of what this issue is about.

**Comment by clarkio** [comment]
Addressed in #83. Closing.
